name: HideLogin
main: com.celeo.hidelogin.HideLogin
author: Celeo
version: 1.3
description: Plugin for hiding people's login messages
commands:
  hiddenlogins:
    description: Checks who is hiding their logins
    usage: /<command> (Must be OP)
  hideme:
    description: Adds you to hidden login list
    usage: /<command> (Must be OP)
  showme:
    description: Removes you from the hidden login list
    usage: /<command> (Must be OP)
  togglelogins:
    description: Removes all login messages
    usage: /<command> [on/off]