name: HideLogin
main: com.celeo.hidelogin.Core
author: Celeo
version: 1.11
description: Plugin for hiding people's login messages
commands:
  hiddenlogs:
    description: Checks who is hiding their logins/out
    usage: /<command>
  hideme:
    description: Adds you to hidden login/out list
    usage: /<command>
  showme:
    description: Removes you from the hidden login/out list
    usage: /<command>
  togglelogs:
    description: Removes all login/out messages
    usage: /<command> [on/off]
  hidemessages:
    description: Blocks login/out messages from coming to you
    usage: /<command>
  showmessages:
    description: Blocks login/out messages from coming to you
    usage: /<command>
  fakelog:
    description: Fakes a logout
    usage: /<command>